### ISSUE TITLE
Cannot find CompositePreprocessing (Docker Env)

### ISSUE THREAD

**Issue by EkicierNico** [CNES/WASP#3]
Hello,
I have an error when I try to use Wasp in a docker : "NameError: Cannot find CompositePreprocessing in the list of OTB Apps". The mesa-libGLU-devel library is installed as you can see in the Dockerfile :

FROM centos:7
RUN yum -y update
RUN yum -y install mesa-libGLU-devel nano zip unzip file git curl
COPY WASP-v1.1.run /
RUN mkdir /wasp
RUN bash WASP-v1.1.run --target /wasp
RUN rm WASP-v1.1.run
COPY EnvWasp.sh /
RUN bash EnvWasp.sh

I add this script (EnvWasp.sh) also to put path in env : 
#!/bin/bash

YOUR_WASP_INSTALL_PATH=/wasp

export PATH=$YOUR_WASP_INSTALL_PATH/bin:$PATH
export OTB_APPLICATION_PATH=$YOUR_WASP_INSTALL_PATH/lib/otb/applications
export LD_LIBRARY_PATH=$YOUR_WASP_INSTALL_PATH/lib

ldd $YOUR_WASP_INSTALL_PATH/lib/otbapp_CompositePreprocessing.so
ldd $YOUR_WASP_INSTALL_PATH/lib/otb/applications/otbapp_CompositePreprocessing.so

Thanks for your help.
Nicolas

**Comment by petket-5** [comment]
Hi Nicolas,

Here is a working example based on docker volumes in order to attach the needed files into the folder.

Dockerfile:
```
FROM centos:7
RUN yum -y update
RUN yum -y upgrade
RUN yum -y install mesa-libGLU-devel nano zip unzip file git curl
COPY WASP-v1.1.run /
RUN bash WASP-v1.1.run --target /wasp
RUN rm WASP-v1.1.run
RUN mkdir /products
RUN mkdir /synthesis
COPY EnvWasp.sh /
```

EnvWasp.sh:
```
#!/bin/bash

YOUR_WASP_INSTALL_PATH=/wasp

export PATH=$YOUR_WASP_INSTALL_PATH/bin:$PATH
export OTB_APPLICATION_PATH=$YOUR_WASP_INSTALL_PATH/lib/otb/applications
export LD_LIBRARY_PATH=$YOUR_WASP_INSTALL_PATH/lib

/wasp/bin/WASP -i `find /products -name "*L2A*MTD_ALL.xml"` -o /synthesis $@
```

Commands:
Build:
```
docker build -t wasp_docker wasp_docker/
```

Run, attaching the input- and output- volumes:
```
docker run -v `pwd`/wasp_docker/inputs:/products -v `pwd`/wasp_docker/synthesis:/synthesis -it wasp_docker:latest bash /EnvWasp.sh
```

Finally, I used the slightly updated version of WASP that I had available on my computer which corrects some bugs mainly for the use of Venus. I just updated the version on the cnes-website, so in order to make sure that everything works, could you please re-download it?

Please tell me whether this works for you.

Kind regards,
Peter

**Comment by EkicierNico** [comment]
Hi Peter,
I downloaded the "new" release from cnes website, I built it in the centos docker and I tested.
From now on, it works fine. :)

Thanks you for your help !
Best regards,

Nicolas
